### ISSUE TITLE
The signup button wasn't working

### ISSUE THREAD

**Issue by ghost** [realfelipe1/Volska#1]

**Comment by realfelipe1** [comment]
Thank you,

**Comment by ghost** [comment]
Np.

**Comment by realfelipe1** [comment]
The sign up button is fake, for the future, im going to make a much-better looking one. From: Nikil SriramSent: Saturday, July 4, 2020 9:19 PMTo: realfelipe1/VolskaCc: realfelipe1; CommentSubject: Re: [realfelipe1/Volska] The signup button wasn't working (#1) Np.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ghost** [comment]
Oh the signup button was fake?

**Comment by realfelipe1** [comment]
Yes, I will send u the link of the new link. Also you might not know this,
the others know this but u might not. Volska is going to get a medium-sized
update which has more features.

**Comment by ghost** [comment]
Yes you have told me thank you for the update.

**Comment by realfelipe1** [comment]
Ok.

**Comment by ghost** [comment]
Post them to Github when you are done so I can see :D

**Comment by realfelipe1** [comment]
Why you can see the code. So no. Also, your friends with Erik and that
would be a leak so no.
